import { useEffect, useState } from "react";
import { BriefcaseBusiness, Target, FileText, TrendingUp, ArrowRight, RefreshCw, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { checkBackendHealth, getJobs, getApplications } from "../api/api";
import { unwrapList, jobTitle, companyName, matchScore, getErrorMessage } from "../utils";
import { ErrorMessage, Loading } from "../components/Feedback";

export default function Dashboard() {
  const [health, setHealth] = useState("checking"); const [jobs, setJobs] = useState([]); const [applications, setApplications] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { setLoading(true); setError(""); const results = await Promise.allSettled([checkBackendHealth(), getJobs("", 50), getApplications()]); if (results[0].status === "fulfilled") setHealth("online"); else setHealth("offline"); if (results[1].status === "fulfilled") setJobs(unwrapList(results[1].value)); if (results[2].status === "fulfilled") setApplications(unwrapList(results[2].value)); const failed = results.find(r => r.status === "rejected"); if (failed) setError(getErrorMessage(failed.reason)); setLoading(false); };
  useEffect(() => { load(); }, []);
  const scored = jobs.map(matchScore).filter(v => v !== null); const strong = scored.filter(v => v >= 70).length; const avg = scored.length ? Math.round(scored.reduce((a,b)=>a+b,0)/scored.length) : 0;
  return <div className="mx-auto max-w-7xl space-y-6">
    <section className="relative overflow-hidden rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="pointer-events-none absolute -right-12 -top-16 h-64 w-64 rounded-full bg-blue-100 blur-3xl"/><div className="relative max-w-2xl"><span className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700"><Sparkles size={14}/> AI Job Hunter</span><h1 className="mt-4 text-2xl font-bold tracking-tight text-slate-900 sm:text-3xl">Your next opportunity starts here.</h1><p className="mt-3 text-sm leading-6 text-slate-500 sm:text-base">Manage your resume, discover relevant jobs, and keep every application organized from one workspace.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/resume" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-700">Upload Resume <ArrowRight size={17}/></Link><Link to="/jobs" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-semibold text-slate-700 hover:bg-slate-50">Explore Jobs</Link><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-50"><RefreshCw size={15}/> Refresh</button></div><p className={`mt-4 text-xs font-semibold ${health === "online" ? "text-emerald-600" : health === "offline" ? "text-rose-600" : "text-slate-500"}`}>● Backend {health === "online" ? "connected" : health === "offline" ? "not reachable" : "checking…"}</p></div></section>
    <ErrorMessage>{error}</ErrorMessage>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={BriefcaseBusiness} title="Jobs Found" value={loading ? "—" : jobs.length} description="Available opportunities"/><StatCard icon={Target} title="Strong Matches" value={loading ? "—" : strong} description="70% or higher match score"/><StatCard icon={FileText} title="Applications" value={loading ? "—" : applications.length} description="Tracked applications"/><StatCard icon={TrendingUp} title="Average Match" value={loading ? "—" : `${avg}%`} description="Across jobs with a score"/></section>
    <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-bold text-slate-900">Recently discovered jobs</h2><p className="mt-1 text-sm text-slate-500">Latest roles returned by your backend.</p></div><Link to="/jobs" className="text-sm font-semibold text-blue-600 hover:text-blue-700">View all <span aria-hidden="true">→</span></Link></div>{loading ? <Loading label="Loading your job dashboard…"/> : jobs.length ? <div className="grid gap-3 md:grid-cols-2">{jobs.slice(0,4).map((job,i)=><div key={job.id ?? job.job_id ?? `${jobTitle(job)}-${i}`} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{jobTitle(job)}</h3><p className="mt-1 text-sm text-slate-500">{companyName(job)}</p></div>{matchScore(job)!==null&&<span className="rounded-lg bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700">{matchScore(job)}% match</span>}</div><p className="mt-3 line-clamp-2 text-sm text-slate-500">{job.description || job.summary || "Open the job listing to review the full description and requirements."}</p></div>)}</div> : <div className="rounded-2xl border border-slate-200 bg-white p-6 text-sm text-slate-500">No jobs returned yet. Open Find Jobs to refresh the job feed.</div>}</section>
    <section><h2 className="mb-4 text-lg font-bold text-slate-900">Get started</h2><div className="grid gap-4 md:grid-cols-3"><QuickAction number="01" title="Upload your resume" description="Extract your experience and skills for matching." to="/resume"/><QuickAction number="02" title="Find matching jobs" description="Search roles and open original application links." to="/jobs"/><QuickAction number="03" title="Track applications" description="Update stages and keep your pipeline organized." to="/applications"/></div></section>
  </div>;
}
function StatCard({icon:Icon,title,value,description}) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon size={19}/></div><p className="mt-5 text-sm text-slate-500">{title}</p><p className="mt-1 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs text-slate-400">{description}</p></div>; }
function QuickAction({number,title,description,to}) { return <Link to={to} className="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:border-blue-200 hover:shadow-md"><span className="text-xs font-bold text-blue-600">{number}</span><h3 className="mt-4 text-base font-semibold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p><div className="mt-4 flex items-center gap-1 text-xs font-semibold text-blue-600">Open <ArrowRight size={14} className="transition-transform group-hover:translate-x-1"/></div></Link>; }
