import { useEffect, useMemo, useState } from "react";
import { Search, MapPin, ExternalLink, BookmarkPlus, Sparkles, RefreshCw } from "lucide-react";
import { getJobs, matchAllJobs, createApplication, autoSaveJobs } from "../api/api";
import { unwrapList, jobTitle, companyName, jobLocation, jobUrl, matchScore, getErrorMessage } from "../utils";
import { ErrorMessage, SuccessMessage, Loading, EmptyState } from "../components/Feedback";

export default function FindJobs() {
  const [jobs,setJobs]=useState([]); const [search,setSearch]=useState(""); const [location,setLocation]=useState(""); const [loading,setLoading]=useState(false); const [matching,setMatching]=useState(false); const [error,setError]=useState(""); const [success,setSuccess]=useState(""); const [saved,setSaved]=useState({}); const [minScore,setMinScore]=useState("all");
  const loadJobs=async()=>{setLoading(true);setError("");setSuccess("");try{const data=await getJobs(search,50);setJobs(unwrapList(data));}catch(e){setError(getErrorMessage(e));}finally{setLoading(false);}};
  useEffect(()=>{loadJobs();},[]);
  const filtered=useMemo(()=>jobs.filter(j=>`${jobTitle(j)} ${companyName(j)} ${jobLocation(j)} ${j.description||""}`.toLowerCase().includes(location.toLowerCase()) && (minScore==="all" || (matchScore(j)!==null&&matchScore(j)>=Number(minScore)))),[jobs,location,minScore]);
  const matchJobs=async()=>{const profile=JSON.parse(localStorage.getItem("ai-job-hunter-profile")||"null");if(!profile){setError("Upload your resume first so the AI can compare jobs with your profile.");return;}setMatching(true);setError("");setSuccess("");try{const data=await matchAllJobs(profile,search,50);const results=unwrapList(data);if(results.length)setJobs(results);else if(Array.isArray(data?.matched_jobs))setJobs(data.matched_jobs);setSuccess("AI matching request completed. Review the scores returned by your backend.");}catch(e){setError(getErrorMessage(e));}finally{setMatching(false);}};
  const saveJob=async(job,index)=>{const key=job.id??job.job_id??`${jobTitle(job)}-${index}`;setError("");setSuccess("");try{await createApplication({company:companyName(job),company_name:companyName(job),position:jobTitle(job),job_title:jobTitle(job),job_url:jobUrl(job),url:jobUrl(job),location:jobLocation(job),status:"Saved",match_score:matchScore(job),notes:"Saved from Find Jobs"});setSaved(p=>({...p,[key]:true}));setSuccess(`Saved “${jobTitle(job)}” to your applications.`);}catch(e){setError(`Could not save this job: ${getErrorMessage(e)}`);}};
  const autoSave=async()=>{setMatching(true);setError("");setSuccess("");try{const data=await autoSaveJobs({search,limit:20,minimumScore:70});setSuccess(data?.message||data?.detail||"Automatic job-save request completed. Check Applications for saved roles.");}catch(e){setError(getErrorMessage(e));}finally{setMatching(false);}};
  return <div className="mx-auto max-w-7xl space-y-5"><div><h1 className="text-2xl font-bold text-slate-900">Find jobs</h1><p className="mt-1 text-sm text-slate-500">Search available roles, request AI matching, and save opportunities to your tracker.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form onSubmit={e=>{e.preventDefault();loadJobs();}} className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="relative block"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search job title or keyword" className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/></label><label className="relative block"><MapPin size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Filter by location or company" className="w-full rounded-xl border border-slate-200 py-3 pl-10 pr-3 text-sm outline-none focus:border-blue-400 focus:ring-2 focus:ring-blue-100"/></label><button className="rounded-xl bg-blue-600 px-5 py-3 text-sm font-semibold text-white hover:bg-blue-700"><Search size={16} className="mr-2 inline"/>Search jobs</button></form><div className="mt-3 flex flex-wrap items-center gap-2"><button onClick={matchJobs} disabled={matching} className="inline-flex items-center gap-2 rounded-lg bg-violet-50 px-3 py-2 text-xs font-semibold text-violet-700 hover:bg-violet-100 disabled:opacity-50"><Sparkles size={14}/>{matching?"Working…":"Match with my resume"}</button><button onClick={autoSave} disabled={matching} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50 disabled:opacity-50"><BookmarkPlus size={14}/> Auto-save 70%+ matches</button><button onClick={loadJobs} disabled={loading} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50"><RefreshCw size={14}/> Refresh feed</button><select value={minScore} onChange={e=>setMinScore(e.target.value)} className="ml-auto rounded-lg border border-slate-200 px-3 py-2 text-xs text-slate-600"><option value="all">Any match score</option><option value="70">70%+ match</option><option value="85">85%+ match</option></select></div></div><ErrorMessage>{error}</ErrorMessage><SuccessMessage>{success}</SuccessMessage>
    <div className="flex items-center justify-between"><p className="text-sm text-slate-500">{loading?"Fetching jobs…":`${filtered.length} jobs shown`}</p></div>{loading?<Loading label="Fetching job listings from your backend…"/>:filtered.length===0?<EmptyState title="No jobs to show" description="Try a broader keyword or refresh the job feed. The backend may return no jobs if the external job source is unavailable."/>:<div className="grid gap-4 lg:grid-cols-2">{filtered.map((job,i)=>{const key=job.id??job.job_id??`${jobTitle(job)}-${i}`;const url=jobUrl(job);const score=matchScore(job);return <article key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-200 hover:shadow-md"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="text-base font-bold text-slate-900">{jobTitle(job)}</h2><p className="mt-1 text-sm font-medium text-slate-600">{companyName(job)}</p></div>{score!==null&&<span className={`shrink-0 rounded-lg px-2.5 py-1 text-xs font-bold ${score>=70?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{score}% match</span>}</div><p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500"><MapPin size={14}/>{jobLocation(job)}{job.job_type||job.type?` · ${job.job_type||job.type}`:""}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-500">{job.description||job.summary||job.tags?.join?.(", ")||"Open the source listing to review the complete job description and requirements."}</p>{job.tags?.length>0&&<div className="mt-3 flex flex-wrap gap-1.5">{job.tags.slice(0,5).map(tag=><span key={tag} className="rounded-md bg-slate-100 px-2 py-1 text-[11px] text-slate-600">{tag}</span>)}</div>}<div className="mt-5 flex flex-wrap gap-2"><button onClick={()=>saveJob(job,i)} disabled={!!saved[key]} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-xs font-semibold text-white hover:bg-blue-700 disabled:bg-emerald-600"><BookmarkPlus size={14}/>{saved[key]?"Saved":"Save application"}</button>{url?<a href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-50">View job <ExternalLink size={14}/></a>:<span className="self-center text-xs text-slate-400">No external job URL provided</span>}</div></article>})}</div>}</div>;
}
