import { useState } from "react";
import { FileText, UploadCloud, CheckCircle2, Download, Trash2 } from "lucide-react";
import { uploadResume } from "../api/api";
import { ErrorMessage, SuccessMessage } from "../components/Feedback";
import { getErrorMessage } from "../utils";

export default function Resume() {
 const [file,setFile]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [profile,setProfile]=useState(()=>{try{return JSON.parse(localStorage.getItem("ai-job-hunter-profile")||"null")}catch{return null}});const [filename,setFilename]=useState(localStorage.getItem("ai-job-hunter-resume-name")||"");
 const handleUpload=async(e)=>{e.preventDefault();if(!file){setError("Choose a PDF resume first.");return;}if(file.type!=="application/pdf"&&!file.name.toLowerCase().endsWith(".pdf")){setError("Only PDF resumes are supported.");return;}setBusy(true);setError("");setSuccess("");try{const data=await uploadResume(file);const nextProfile=data?.profile||data?.resume_profile||data?.candidate_profile||data?.analysis||data?.data?.profile||data;localStorage.setItem("ai-job-hunter-profile",JSON.stringify(nextProfile));localStorage.setItem("ai-job-hunter-resume-name",file.name);setProfile(nextProfile);setFilename(file.name);setSuccess(data?.message||"Resume uploaded and analyzed successfully.");setFile(null);e.target.reset();}catch(err){setError(getErrorMessage(err));}finally{setBusy(false);}};
 const clearProfile=()=>{localStorage.removeItem("ai-job-hunter-profile");localStorage.removeItem("ai-job-hunter-resume-name");setProfile(null);setFilename("");setSuccess("Saved local resume profile cleared.");setError("");};
 const downloadProfile=()=>{const blob=new Blob([JSON.stringify(profile,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="candidate-profile.json";a.click();URL.revokeObjectURL(url);};
 return <div className="mx-auto max-w-5xl space-y-5"><div><h1 className="text-2xl font-bold text-slate-900">My resume</h1><p className="mt-1 text-sm text-slate-500">Upload a PDF to let the backend extract and analyze your candidate profile.</p></div><ErrorMessage>{error}</ErrorMessage><SuccessMessage>{success}</SuccessMessage><div className="grid gap-5 lg:grid-cols-[0.9fr_1.1fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><UploadCloud size={21}/></div><div><h2 className="font-bold text-slate-900">Upload resume</h2><p className="text-xs text-slate-500">PDF format · Keep your latest version</p></div></div><form onSubmit={handleUpload} className="mt-6 space-y-4"><label className="flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 p-5 text-center transition hover:border-blue-400 hover:bg-blue-50/50"><FileText size={30} className="text-blue-600"/><span className="mt-3 text-sm font-semibold text-slate-800">{file?file.name:"Choose your PDF resume"}</span><span className="mt-1 text-xs text-slate-500">Click to browse your computer</span><input type="file" accept="application/pdf,.pdf" className="sr-only" onChange={e=>{setFile(e.target.files?.[0]||null);setError("");}}/></label><button type="submit" disabled={busy||!file} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50">{busy?"Uploading and analyzing…":"Upload and analyze resume"}</button><p className="text-xs leading-5 text-slate-400">AI analysis requires an available Gemini API quota. If the backend reports a quota error, the PDF may have uploaded but analysis can fail.</p></form>{filename&&<div className="mt-5 flex items-start gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><CheckCircle2 size={18} className="mt-0.5 text-emerald-600"/><div className="min-w-0"><p className="text-sm font-semibold text-emerald-800">Current saved resume</p><p className="break-all text-xs text-emerald-700">{filename}</p></div></div>}</section>
 <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold text-slate-900">Extracted candidate profile</h2><p className="mt-1 text-xs text-slate-500">Used by AI matching and resume customization.</p></div>{profile&&<div className="flex gap-2"><button onClick={downloadProfile} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-50"><Download size={14}/> Export JSON</button><button onClick={clearProfile} className="inline-flex items-center gap-1.5 rounded-lg border border-rose-200 px-3 py-2 text-xs font-semibold text-rose-600 hover:bg-rose-50"><Trash2 size={14}/> Clear</button></div>}</div>{profile?<pre className="mt-5 max-h-[480px] overflow-auto rounded-xl bg-slate-950 p-4 text-xs leading-5 text-emerald-200">{JSON.stringify(profile,null,2)}</pre>:<div className="mt-5 rounded-xl border border-dashed border-slate-300 px-5 py-12 text-center"><FileText size={30} className="mx-auto text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-700">No profile saved yet</p><p className="mt-1 text-xs text-slate-500">Upload your PDF to populate this panel.</p></div>}</section></div></div>;
}
